# Generated by Django 4.1.1 on 2022-11-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='created',
        ),
    ]
