# Generated by Django 4.1.1 on 2022-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_customer_alter_newsletter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
